# An SSL Enabled HTML Website
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-ssl-website
  labels: null
spec:
  replicas: 1
  strategy: null
  selector:
    matchLabels:
      app: ssl-website
  template:
    metadata:
      labels:
        app: ssl-website
        env: dev
    spec:
      containers:
        - name: container-ssl-website
          image: tanvisinghny/ssl-website
          ports:
            - containerPort: 80
            - containerPort: 443
---
# An Azure Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: azure-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: ssl-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: HTTP
  - protocol: TCP
    port: 443
    targetPort: 443
    name: HTTPS
    
